# Generated by Django 2.1.5 on 2021-08-18 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.CharField(max_length=225)),
                ('email_host_password', models.CharField(max_length=225)),
                ('email_host', models.CharField(max_length=225)),
                ('email_port', models.CharField(max_length=225)),
                ('email_server', models.CharField(max_length=225)),
                ('email_backend', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmailUsers',
            },
        ),
    ]
