# Generated by Django 2.1.5 on 2021-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailusers',
            name='email_prefix',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailusers',
            name='email_host_user',
            field=models.EmailField(max_length=225),
        ),
    ]
