# Generated by Django 2.1.5 on 2021-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20210818_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailusers',
            name='email_default_text',
            field=models.TextField(default='default_email'),
            preserve_default=False,
        ),
    ]
